# Generated by Django 4.2.7 on 2024-03-18 09:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item_proce",
            new_name="item_price",
        ),
    ]
